version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - media_volume:/home/app/web/project/media
      - static_volume:/home/app/web/project/static
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    environment:
      - TZ=Asia/Yekaterinburg
  nginx:
    build: ./nginx
    volumes:
      - media_volume:/home/app/web/project/media
      - static_volume:/home/app/web/project/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
    driver: local
    driver_opts:
      type: none
      device: E:\UNIVERSITY\DIPLOM\SOWA\web\project\media
      o: bind
