version: '3'
services:
    flask:
      build: ./backend
      container_name: backend-flask
      environment:
        - FLASK_ENV=development
        - PYTHONUNBUFFERED=True
      restart: on-failure
      volumes:
        - ./backend:/backend
      ports:
        - "5000:5000"
      command: gunicorn main:"create_flask_app()" -b 0.0.0.0:5000 --reload